version: "3.5"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
        
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  
  todo-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Todos.Db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong_password_123!"
      
  
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
